image: jojomi/hugo

stages:
  - build
  - deploy

build:
  stage: build
  script:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt install -y nodejs
  - hugo version
  - git submodule update --init --recursive
  - npm install
  - hugo -d public_html
  artifacts:
    paths:
    - public_html
  only:
  - master
  when: manual
  
deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -u $FTP_LOGIN,$FTP_PASSWORD $FTP_HOST -e "mirror -v --parallel=2 -e -R --ignore-time -p ./public_html/ public_hugo/ ; quit"
    - echo "deployment complete"
  dependencies:
    - build
  when: manual

