baseURL = "https://nws-akarah-preprod.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "nws-theme"
title = "Normandie Web School • L'école des métiers du numérique"
weight = 1
[[menu.desktop]]
URL = "cursus"
name = "Les cursus"
weight = 2
[[menu.desktop]]
name = "Demande d'inscription"
weight = 8
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 7
[[menu.desktop]]
URL = "entreprises"
name = "Les entreprises"
weight = 4
#[[menu.desktop]]
#URL = "etudiants"
#name = "Nos étudiants"
#weight = 3
[[menu.desktop]]
URL = "cursus"
name = "Les cursus"
weight = 2
[[menu.desktop]]
URL = 'cursus'
name = "Étudier à la NWS"
parent = "Les cursus"
weight = 1
[[menu.desktop]]
name = "Bachelor design"
parent = "Les cursus"
weight = 4
[[menu.desktop]]
name = "Bachelor développement"
parent = "Les cursus"
weight = 3
[[menu.desktop]]
URL = "marketing"
name = "Bachelor marketing"
parent = "Les cursus"
weight = 2
[[menu.main]]
name = "Master Expert digital"
parent = "Les cursus"
weight = 5

[[menu.main]]
name = "Bachelor design"
parent = "Les cursus"
weight = 4
[[menu.main]]
name = "Bachelor développement"
parent = "Les cursus"
weight = 3
[[menu.main]]
URL = "marketing"
name = "Bachelor marketing"
parent = "Les cursus"
weight = 2
[[menu.main]]
name = "Cursus intital"
parent = "Les cursus"
weight = 1
[[menu.main]]
name = "Demande d'inscription"
weight = 8
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 6
[[menu.main]]
URL = "agenda"
name = "Agenda"
weight = 5
[[menu.main]]
URL = "entreprises"
name = "Les entreprises"
weight = 4
#[[menu.main]]
#URL = "etudiants"
#name = "Nos étudiants"
#weight = 3
[[menu.main]]
URL = "cursus"
name = "Les cursus"
weight = 2

[[menu.top]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.top]]
URL = "faq"
name = "FAQ"
weight = 3
[[menu.top]]
URL = "documentation"
name = "Documentation"
weight = 2
[[menu.top]]
URL = "agenda"
name = "Agenda"
weight = 1
[params]
abstract = "Grâce à une vision transverse des différents métiers du numérique dans un monde en perpétuel mutation, la Normandie Web School."
address = "Seine Innopolis <br/> 72 Rue de la République <br/> 76140 Le Petit-Quevilly"
author = "Akarah"
copyright = "Normandie Web School © 2020"
description = "This is meta description"
email = "contact@normandiewebschool.fr"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/logo_nws.png"
phone = "02.79.02.73.78"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
