# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: |
          npm install
          hugo -d public_html --baseURL=https://normandiewebschool.fr --minify

      - name: LFTP Deploy
        # You may pin to the exact commit or the version.
        # uses: MajorVengeance/Ftp-Deploy-Action@27822b6d8e1966e0158671693f32a681a8c7fabf
        uses: MajorVengeance/Ftp-Deploy-Action@v0.2.3-alpha
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_LOGIN }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          # The local folder to copy
          local_source_dir: ./public_html/
          # The remote folder
          dist_target_dir: /
