# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: bpack/hugo-npm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          hugo version
          npm install
          hugo -d public_html --baseURL=https://normandiewebschool.fr

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: |
          apt-get update -qq && apt-get install -y -qq lftp
          lftp -u ${{ secrets.FTP_LOGIN }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "mirror -v --parallel=2 -e -R --ignore-time -p ./public_html/ / ; quit"
          echo "deployment complete"
